export const users = [
  {
    id: 1,
    genre: "homme",
    name: "Gibert Victor",
    role: "super admin",
    state: "En ligne",
    email: "adresse.emailt@example.com",
    password: "bob@martin",
    lastLogin: "2024-08-10 14:23",
    registrationDate: "2024-01-15",
  },
  {
    id: 2,
    genre: "homme",
    name: "Bob Martin",
    role: "abonné",
    state: "Hors ligne",
    email: "bob.martin@example.com",
    password: "bob@martin",
    lastLogin: "2024-08-10 14:23",
    registrationDate: "2024-02-20",
  },
  {
    id: 3,
    genre: "femme",
    name: "Claire Petit",
    role: "abonné",
    state: "En ligne",
    email: "claire.petit@example.com",
    password: "bob@martin",
    lastLogin: "2024-08-10 14:23",
    registrationDate: "2024-03-12",
  },
  {
    id: 4,
    genre: "homme",
    name: "David Lefebvre",
    role: "abonné",
    state: "En ligne",
    email: "david.lefebvre@example.com",
    password: "bob@martin",
    lastLogin: "2024-08-10 14:23",
    registrationDate: "2024-04-05",
  },
  {
    id: 5,
    genre: "femme",
    name: "Emma Bernard",
    role: "editeur",
    state: "Hors ligne",
    email: "emma.bernard@example.com",
    password: "bob@martin",
    lastLogin: "2024-08-10 14:23",
    registrationDate: "2024-05-25",
  },
  {
    id: 6,
    genre: "homme",
    name: "François Dubois",
    role: "abonné",
    state: "En ligne",
    email: "francois.dubois@example.com",
    password: "bob@martin",
    lastLogin: "2024-08-10 14:23",
    registrationDate: "2024-06-10",
  },
  {
    id: 7,
    genre: "femme",
    name: "Géraldine Morin",
    role: "abonné",
    state: "En ligne",
    email: "geraldine.morin@example.com",
    password: "bob@martin",
    lastLogin: "2024-08-10 14:23",
    registrationDate: "2024-07-22",
  },
  {
    id: 8,
    genre: "homme",
    name: "Hugo Marchand",
    role: "abonné",
    state: "En ligne",
    email: "hugo.marchand@example.com",
    password: "bob@martin",
    lastLogin: "2024-08-10 14:23",
    registrationDate: "2024-08-30",
  },
  {
    id: 9,
    genre: "femme",
    name: "Isabelle Moreau",
    role: "abonné",
    state: "Hors ligne",
    email: "isabelle.moreau@example.com",
    password: "bob@martin",
    lastLogin: "2024-08-10 14:23",
    registrationDate: "2024-09-18",
  },
  {
    id: 10,
    genre: "homme",
    name: "Julien Lemoine",
    role: "editeur",
    state: "Hors ligne",
    email: "julien.lemoine@example.com",
    password: "bob@martin",
    lastLogin: "2024-08-10 14:23",
    registrationDate: "2024-10-05",
  },
  {
    id: 11,
    genre: "femme",
    name: "Katherine Bernard",
    role: "admin",
    state: "Hors ligne",
    email: "katherine.bernard@example.com",
    password: "bob@martin",
    lastLogIn: "2024-11-12",
    lastLogin: "2024-08-10 14:23",
    registrationDate: "2024-11-12",
  },
  {
    id: 12,
    genre: "homme",
    name: "Louis Roux",
    role: "admin",
    state: "En ligne",
    email: "louis.roux@example.com",
    password: "bob@martin",
    lastLogin: "2024-08-10 14:23",
    registrationDate: "2024-12-01",
  },
  {
    id: 13,
    genre: "femme",
    name: "Marie Lefèvre",
    role: "abonné",
    state: "Hors ligne",
    email: "marie.lefevre@example.com",
    password: "bob@martin",
    lastLogin: "2024-08-10 14:23",
    registrationDate: "2024-01-20",
  },
  {
    id: 14,
    genre: "homme",
    name: "Nicolas Dubois",
    role: "editeur",
    state: "En ligne",
    email: "nicolas.dubois@example.com",
    password: "bob@martin",
    lastLogin: "2024-08-10 14:23",
    registrationDate: "2024-02-14",
  },
  {
    id: 15,
    genre: "femme",
    name: "Olivia Bernard",
    role: "abonné",
    state: "En ligne",
    email: "olivia.bernard@example.com",
    password: "bob@martin",
    lastLogin: "2024-08-10 14:23",
    registrationDate: "2024-03-27",
  },
  {
    id: 16,
    genre: "homme",
    name: "Paul Martin",
    role: "abonné",
    state: "En ligne",
    email: "paul.martin@example.com",
    password: "bob@martin",
    lastLogin: "2024-08-10 14:23",
    registrationDate: "2024-04-17",
  },
  {
    id: 17,
    genre: "homme",
    name: "Quentin Petit",
    role: "abonné",
    state: "En ligne",
    email: "quentin.petit@example.com",
    password: "bob@martin",
    lastLogin: "2024-08-10 16:23",
    registrationDate: "2024-05-19",
  },
  {
    id: 18,
    genre: "femme",
    name: "Rachel Lefebvre",
    role: "abonné",
    state: "Hors ligne",
    email: "rachel.lefebvre@example.com",
    password: "bob@martin",
    lastLogin: "2024-08-10 14:23",
    registrationDate: "2024-06-30",
  },
  {
    id: 19,
    genre: "femme",
    name: "Sophie Morin",
    role: "abonné",
    state: "En ligne",
    email: "sophie.morin@example.com",
    password: "bob@martin",
    lastLogin: "2024-08-10 14:23",
    registrationDate: "2024-07-25",
  },
  {
    id: 20,
    genre: "homme",
    name: "Thomas Dubois",
    role: "abonné",
    state: "Hors ligne",
    email: "thomas.dubois@example.com",
    password: "bob@martin",
    lastLogin: "2024-08-10 14:23",
    registrationDate: "2024-08-09",
  },
];
