export const users = [
  {
    id: 1,
    genre: "homme",
    pseudo: "vgibert",
    lastname: "Gibert",
    firstname: "Victor",
    role: "admin",
    state: "En ligne",
    statut: "actif",
    email: "adresse.emailt@example.com",
    password: "bob@martin",
    lastLogin: "2024-08-10 14:23",
    registrationDate: "01-01-2024",
  },
  {
    id: 2,
    genre: "homme",
    pseudo: "bmartin",
    lastname: "Martin",
    firstname: "Bob",
    role: "abonné",
    state: "Hors ligne",
    statut: "suspended",
    email: "bob.martin@example.com",
    password: "bob@martin",
    lastLogin: "2024-08-10 14:23",
    registrationDate: "20-02-2024",
  },
  {
    id: 3,
    genre: "femme",
    pseudo: "pclaire",
    lastname: "Petit",
    firstname: "Claire",
    role: "abonné",
    state: "En ligne",
    statut: "actif",
    email: "claire.petit@example.com",
    password: "bob@martin",
    lastLogin: "2024-08-10 14:23",
    registrationDate: "12-03-2024",
  },
  {
    id: 4,
    genre: "homme",
    pseudo: "ldavid",
    lastname: "Lefebvre",
    firstname: "David",
    role: "abonné",
    state: "En ligne",
    statut: "suspended",
    email: "david.lefebvre@example.com",
    password: "bob@martin",
    lastLogin: "2024-08-10 14:23",
    registrationDate: "04-05-2024",
  },
  {
    id: 5,
    genre: "femme",
    pseudo: "bemma",
    lastname: "Bernard",
    firstname: "Emma",
    role: "editeur",
    state: "Hors ligne",
    statut: "inactif",
    email: "emma.bernard@example.com",
    password: "bob@martin",
    lastLogin: "2024-08-10 14:23",
    registrationDate: "25-05-2024",
  },
  {
    id: 6,
    genre: "homme",
    pseudo: "dfrançois",
    lastname: "Dubois",
    firstname: "François",
    role: "abonné",
    state: "En ligne",
    statut: "actif",
    email: "francois.dubois@example.com",
    password: "bob@martin",
    lastLogin: "2024-08-10 14:23",
    registrationDate: "10-06-2024",
  },
  {
    id: 7,
    genre: "femme",
    pseudo: "mgéraldine",
    lastname: "Morin",
    firstname: "Géraldine",
    role: "abonné",
    state: "Hors ligne",
    statut: "inactif",
    email: "geraldine.morin@example.com",
    password: "bob@martin",
    lastLogin: "2024-08-10 14:23",
    registrationDate: "22-07-2024",
  },
  {
    id: 8,
    genre: "homme",
    pseudo: "mhugo",
    lastname: "Marchand",
    firstname: "Hugo",
    role: "abonné",
    state: "En ligne",
    statut: "actif",
    email: "hugo.marchand@example.com",
    password: "bob@martin",
    lastLogin: "2024-08-10 14:23",
    registrationDate: "30-08-2024",
  },
  {
    id: 9,
    genre: "femme",
    pseudo: "misabelle",
    lastname: "Moreau",
    firstname: "Isabelle",
    role: "abonné",
    state: "Hors ligne",
    statut: "inactif",
    email: "isabelle.moreau@example.com",
    password: "bob@martin",
    lastLogin: "2024-08-10 14:23",
    registrationDate: "18-09-2024",
  },
  {
    id: 10,
    genre: "homme",
    pseudo: "ljulien",
    lastname: "Lemoine",
    firstname: "Julien",
    role: "editeur",
    state: "Hors ligne",
    statut: "actif",
    email: "julien.lemoine@example.com",
    password: "bob@martin",
    lastLogin: "2024-08-10 14:23",
    registrationDate: "10-05-2024",
  },
  {
    id: 11,
    genre: "femme",
    pseudo: "bkatherine",
    lastname: "Bernard",
    firstname: "Katherine",
    role: "admin",
    state: "Hors ligne",
    statut: "actif",
    email: "katherine.bernard@example.com",
    password: "bob@martin",
    lastLogIn: "2024-11-12",
    lastLogin: "2024-08-10 14:23",
    registrationDate: "12-01-2024",
  },
  {
    id: 12,
    genre: "homme",
    pseudo: "rlouis",
    lastname: "Roux",
    firstname: "Louis",
    role: "admin",
    state: "En ligne",
    statut: "actif",
    email: "louis.roux@example.com",
    password: "bob@martin",
    lastLogin: "2024-08-10 14:23",
    registrationDate: "01-03-2024",
  },
  {
    id: 13,
    genre: "femme",
    pseudo: "lmarie",
    lastname: "Lefèvre",
    firstname: "Marie",
    role: "abonné",
    state: "Hors ligne",
    statut: "actif",
    email: "marie.lefevre@example.com",
    password: "bob@martin",
    lastLogin: "2024-08-10 14:23",
    registrationDate: "2024-01-20",
  },
  {
    id: 14,
    genre: "homme",
    pseudo: "dnicolas",
    lastname: "Dubois",
    firstname: "Nicolas",
    role: "editeur",
    state: "En ligne",
    statut: "actif",
    email: "nicolas.dubois@example.com",
    password: "bob@martin",
    lastLogin: "2024-08-10 14:23",
    registrationDate: "2024-02-14",
  },
  {
    id: 15,
    genre: "femme",
    pseudo: "bolivia",
    lastname: "Bernard",
    firstname: "Olivia",
    role: "abonné",
    state: "En ligne",
    statut: "actif",
    email: "olivia.bernard@example.com",
    password: "bob@martin",
    lastLogin: "2024-08-10 14:23",
    registrationDate: "2024-03-27",
  },
  {
    id: 16,
    genre: "homme",
    pseudo: "mpaul",
    lastname: "Martin",
    firstname: "Paul",
    role: "abonné",
    state: "En ligne",
    statut: "actif",
    email: "paul.martin@example.com",
    password: "bob@martin",
    lastLogin: "2024-08-10 14:23",
    registrationDate: "17-04-2024",
  },
  {
    id: 17,
    genre: "homme",
    pseudo: "pquentin",
    lastname: "Petit",
    firstname: "Quentin",
    role: "abonné",
    state: "Hors ligne",
    statut: "inactif",
    email: "quentin.petit@example.com",
    password: "bob@martin",
    lastLogin: "2024-08-10 16:23",
    registrationDate: "19-05-2022",
  },
  {
    id: 18,
    genre: "femme",
    pseudo: "pquentin",
    lastname: "Lefebvre",
    firstname: "Rachel",
    role: "abonné",
    state: "Hors ligne",
    statut: "actif",
    email: "rachel.lefebvre@example.com",
    password: "bob@martin",
    lastLogin: "2024-08-10 14:23",
    registrationDate: "30-06-2024",
  },
  {
    id: 19,
    genre: "femme",
    pseudo: "msophie",
    lastname: "Morin",
    firstname: "Sophie",
    role: "abonné",
    state: "En ligne",
    statut: "actif",
    email: "sophie.morin@example.com",
    password: "bob@martin",
    lastLogin: "2024-08-10 74:23",
    registrationDate: "25-06-2024",
  },
  {
    id: 20,
    genre: "homme",
    pseudo: "dthomas",
    lastname: "Dubois",
    firstname: "Thomas",
    role: "abonné",
    state: "Hors ligne",
    statut: "inactif",
    email: "thomas.dubois@example.com",
    password: "bob@martin",
    lastLogin: "2024-08-10 14:23",
    registrationDate: "2024-08-09",
  },
];
